# Generated by Django 2.0.3 on 2018-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='funding',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
